config/routes.rb
BugCenter::Application.routes.draw do

  resources :sessions, only: [:new, :create, :destroy]
  resources :microposts, only: [:create, :destroy]
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :relationships, only: [:create, :destroy]
  resources :bugs
  resources :products
  resources :surveys
  root to: 'static_pages#home'
  match '/help',    to: 'static_pages#help'
  match '/about',   to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'

  match '/signup',  to: 'users#new'

  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

  match '/bugreport', to: 'bugs#new'

  match '/productnew', to:'products#new'

  match '/startsurvey', to:'surveys#new'

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  	if signed_in?
      @micropost  = current_user.microposts.build
      @feed_items = current_user.feed.paginate(page: params[:page])
    end
  end

  def help
  end

  def about
  end

  def contact

  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<% provide(:title, 'About Us') %>
<h1>About Us</h1>
<p>Welcome to the <a href="http://reconinstruments.com">Recon World</a>
</p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact Us') %>
<h1>Contact</h1>
<p>
	Trust our instruments to contact us :)
</p>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>
<h1>Help</h1>
<p>
	Find Us :)
</p>

app/views/static_pages/home.html.erb
<% provide(:title, "Home") %>
<% if signed_in? %>
  <!-- if the user is signed-in -->
  <div class="row">
    <aside class="span4">
      <section>
        <%= render 'shared/user_info' %>
      </section>
      <section>
        <%= render 'shared/stats' %>
      </section>
      <section>
        <%= render 'shared/micropost_form' %>
      </section>
    </aside>
    <div class="span8">
      <h3>Micropost Feed</h3>
      <%= render 'shared/feed' %>
    </div>
  </div>  
<% else %>
  <!-- If the user is not sign-in -->
  <div class="center hero-unit">
    <h1>Welcome to the <br/> Recon Instruments Center</h1>

    <h2>
      You can find some report here and also report some bugs
    </h2>

    <%= link_to "Sign in now!", signin_path, class: "btn btn-large btn-primary" %> <br/>
    If you are not registered, please <%= link_to "sign up.", signup_path%>
  </div>

  <%= link_to image_tag("rails.png", alt: "Rails"), 'http://rubyonrails.org/' %>
<% end %> 