config/routes.rb
BugCenter::Application.routes.draw do

  resources :sessions, only: [:new, :create, :destroy]
  resources :microposts, only: [:create, :destroy]
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :relationships, only: [:create, :destroy]
  resources :bugs
  resources :products
  resources :surveys
  root to: 'static_pages#home'
  match '/help',    to: 'static_pages#help'
  match '/about',   to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'

  match '/signup',  to: 'users#new'

  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

  match '/bugreport', to: 'bugs#new'

  match '/productnew', to:'products#new'

  match '/startsurvey', to:'surveys#new'

end

app/models/bug.rb
# == Schema Information
#
# Table name: bugs
#
#  id          :integer          not null, primary key
#  bug_title   :string(255)
#  bug_type    :string(255)
#  version     :string(255)
#  product     :string(255)
#  description :text(255)
#  steps       :text(255)
#  priority    :string(255)
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  user_id     :integer
#

class Bug < ActiveRecord::Base
  attr_accessible :bug_title, :bug_type, :description, :priority, :product, :steps, :version
  belongs_to :user
  
  #validation of the data
  validates :bug_title, presence: true, length: { maximum: 255 }
  validates :bug_type, presence: true,  length: { maximum: 50 }
  validates :description, presence: true
  validates :version, presence: true,  length: { maximum: 50 }
  #validates :steps, presence: true
  validates :priority, presence: true,  length: { maximum: 50 }
  validates :product, presence: true, length: { maximum: 50 }
  validates :user_id, presence: true

  default_scope order: 'bugs.created_at DESC'

  #Data for DropDown Menu
  BUGTYPE = ['Bug','Improvement']
  PRIORITY = ['Blocker','Critical','Major','Minor','Nevermind, it\'s not really important']
end

app/controllers/bugs_controller.rb
class BugsController < ApplicationController
  #function for the new bug
  def new
  	@bug=Bug.new
  end

  #permit to show a bug
  def show
    @bug = Bug.find(params[:id])
  end

  def create
    @bug = current_user.bugs.build(params[:bug])
    if @bug.save
      flash[:success] = "Bug created!"
      redirect_to @bug
    else
      render 'new'
    end
  end

  #Permit to index all bugs
  def index
    @bugs = Bug.paginate(page: params[:page])
  end

  def edit
    @bug = Bug.find(params[:id])
  end

  def update
    @bug = Bug.find(params[:id])
    if @bug.update_attributes(params[:bug])
      flash[:success] = "Bug updated"
      redirect_to @bug
    else
      render 'edit'
    end
  end
end

app/helpers/bugs_helper.rb
module BugsHelper
end

app/views/bugs/_bug.html.erb
<li>
  <%= link_to bug.bug_title, bug %>
</li>

app/views/bugs/edit.html.erb
<% if current_user.intuser? || current_user.id == @bug.user_id %>
    <% provide(:title, "Edit bug") %> 
    <h1>Update your bug</h1>

    <div class="row">
      <div class="span6 offset3">
        <%= form_for(@bug) do |f| %>
          <%= render 'shared/error_messages', object: f.object %>
            <%= f.label :bug_title %>
            <%= f.text_field :bug_title %>

            <%= f.label :bug_type %>
            <%= f.collection_select :bug_type, Bug::BUGTYPE, :to_s, :to_s, :include_blank => false %>

            <%= f.label :priority %>
            <%= f.collection_select :priority, Bug::PRIORITY, :to_s, :to_s, :include_blank => false %>

            <%= f.label :product %>
            <%= f.text_field :product %>

            <%= f.label :version %>
            <%= f.text_field :version %>

            <%= f.label :description %>
            <%= f.text_area :description, :size => 5 %>


            <%= f.label "Steps to reproduce the bug, if it's possible" %>
            <%= f.text_area :steps %>


            <%= f.submit "Update the bug", class: "btn btn-large btn-primary" %>
        <% end %>
      </div>
    </div>
<% else %>
    <% provide(:title, "403" ) %>
    <h2>Sorry, you don't have the rights. Please contact the adminstrators.</h2>
<% end %>

app/views/bugs/index.html.erb
<% if current_user.authouser? || current_user.intuser? %>
	<% provide(:title, 'All bugs') %>
	<h1>All bugs</h1>

	<%= will_paginate %>

	<ul class="bugs">
	  <%= render @bugs %>
	</ul>

	<%= will_paginate %>
<% else %>
	<% provide(:title, "403" ) %>
	<h2>Sorry, you don't have the rights. Please contact the administrators.</h2>
<% end %>

app/views/bugs/new.html.erb
<!--#  bug_title   :string(255)
#  bug_type    :string(255)
#  version     :string(255)
#  product     :string(255)
#  description :text(255)
#  steps       :text(255)
#  priority    :string(255)-->
<% if current_user.authouser? || current_user.intuser? %>
  <% provide(:title, 'Bug Report') %>
  <h1>Please report your annoying little thing to daddy</h1>

  <div class="row">
    <div class="span6 offset3">
      <%= form_for(@bug) do |f| %>
        <%= render 'shared/error_messages', object: f.object %>
        <%= f.label :bug_title %>
        <%= f.text_field :bug_title %>

        <%= f.label :bug_type %>
        <%= f.collection_select :bug_type, Bug::BUGTYPE, :to_s, :to_s, :include_blank => false %>

        <%= f.label :priority %>
        <%= f.collection_select :priority, Bug::PRIORITY, :to_s, :to_s, :include_blank => false %>

        <%= f.label :product %>
        <%= f.text_field :product %>

        <%= f.label :version %>
        <%= f.text_field :version %>

        <%= f.label :description %>
        <%= f.text_area :description, :size => 5 %>


        <%= f.label "Steps to reproduce the bug, if it's possible" %>
        <%= f.text_area :steps %>


        <%= f.submit "Create the bug", class: "btn btn-large btn-primary" %>
      <% end %>
    </div>
  </div>
<% else %>
  <% provide(:title, "403" ) %>
  <h2>Sorry, you don't have the rights. Please contact the administrators.</h2>
<% end %>

app/views/bugs/show.html.erb
<% if signed_in? %>
	<% if current_user.authouser? || current_user.intuser? %>
		<% provide(:title, @bug.bug_title ) %>
		<span style="text-decoration:underline;">Bug Title:</span>  <%= @bug.bug_title %>
		<span style="text-decoration:underline;">By:</span> <%= User.find(@bug.user_id).name %>
		<br/>
		<span style="text-decoration:underline;">Bug Type:</span>  <%= @bug.bug_type %>
		<span style="text-decoration:underline;margin-left:30px;">Product:</span>  <%= @bug.product %>
		<span style="text-decoration:underline;margin-left:30px;">Version:</span>  <%= @bug.version %>
		<span style="text-decoration:underline;margin-left:30px;">Priority:</span>  <%= @bug.priority %><br/>
		<span style="text-decoration:underline;">Description:</span>
		<div style="width:100%;min-height=50px;height:auto;border:1px solid black;"><%= @bug.description %></div>
		<span style="text-decoration:underline;">Steps to reproduce:</span>
		<div style="width:100%;min-height=50px;height:auto;border:1px solid black;"><%= @bug.steps %></div>
		<br/>
		<!-- if the user is an internal user or the user reports the bug then allowed the edit --> 
		<% if current_user.intuser? || current_user.id == @bug.user_id %>
			<%= button_to "Edit the bug", edit_bug_path, :method => "get", class: "btn btn-large btn-primary" %>
		<% end %>
	<% else %>
		<% provide(:title, "403" ) %>
		<h2>Sorry, you don't have the rights. Please contact the adminstrators.</h2>
	<% end %>
<% end %>